- path: /
  title: Revealry Demo
  description: This is a demo of Revealry, a template for personal website

- path: /intro/index
  title: About Me
  description: Learn more about me.

- path: /links/index
  title: Some Links about me
  description: Find some useful links about me.

- path: /blog/index
  title: My Blog Posts
  description: Read my blog posts.